POST http://localhost:39889/odata/v4/service/risk/addItem
Content-Type: application/json
Connection: keep-alive

{
    "descr":"descr",
    "title": "title",
    "quantity": 20
}


###
GET http://localhost:39449/odata/v4/service/risk/getProducts()


###
GET http://localhost:39449/odata/v4/service/risk/getOnPremise()